FileVersion = 1

[Project]
Name = "msf_gif-beef"
DefaultNamespace = "msf_gif"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\msf_gif_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\msf_gif.lib"]